# -*- coding: utf-8 -*-
"""Pandas

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IkI8Xz6zhqAo_Ns2KxmDv-mrHbZPZbC8
"""

import pandas as pd
from pandas.plotting import scatter_matrix
import os
import sys
import csv
from collections import Counter
from datetime import datetime

data = pd.read_csv('sars_ani_data.csv')


def casosCaes():
    count = 0
    dog = data[data['host_com_orig '] == 'dog']
    dog['number_cases'] = pd.to_numeric(dog['number_cases'], errors='coerce')
    total_casos = dog['number_cases'].sum()
    return total_casos
casosCaes()

def eventosFelideos(data):
    felideos = data[data['family'] == 'Felidae']
    especies = felideos['host_colloq'].unique()
    eventos = []

    for especie in especies:
        num_eventos = felideos[felideos['host_colloq'] == especie].shape[0]
        eventos.append((especie, num_eventos))

    eventos = sorted(eventos, key=lambda x: x[1], reverse=True)

    return eventos
eventosFelideos(data)

animais_classe = data['living_conditions']
animais_classe.unique()

def maisHumanos(data):
    animais_humanos = data[data['source_of_infection'] == 'human']
    resultados = animais_humanos.groupby('living_conditions')['country_name'].apply(lambda x: x.value_counts().idxmax()).to_dict()
    return resultados
maisHumanos(data)

"""Para as demais classes de animais, não haviam eventos de contacto com humanos"""
